<a href="https://colab.research.google.com/github/saghar-trade/Unsupervised-Learning/blob/main/PCA_manual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from mpl_toolkits import mplot3d
from numpy.linalg import svd
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [2]:
def Manual_PCA(x,k=2):
  """a function to perform PCA on
  Argument:
  x : input data, numpy array of shape (m,n)
  k : number of components
  Return:
  projection of x into a k-dimensional space
  """
  m=x.shape[0]
  n=x.shape[1]
  x_norm=x-x.mean(axis=0)   #step1:zero center data (remove mean)

  sigma=(x_norm.T@x_norm)/m #step2 :compute covariance matrix
  U, S,VT= svd(sigma)       #step3: singular value decomposition
  x_proj=x_norm@ U[:,:k]   #project data
  V=np.transpose(VT)
  return x_proj , U,S,V

In [3]:
x=np.array([[-2,-1,0,1,2],
            [2,2,2,2,1],
            [1,1,1,0,1],
            [5,5,5,2,0],
            [1,1,0,2,2],
            [0,0,0,3,3],
            [0,-1,0,-1,1]])

In [4]:
x_proj,U,S,V=Manual_PCA(x,k=2)
print(x_proj)

[[ 3.66908224 -0.06787159]
 [-1.7831874  -0.39600759]
 [ 0.15270574  1.30091115]
 [-7.01882138  0.2199571 ]
 [ 0.5989285  -1.02074083]
 [ 1.84129648 -2.27776767]
 [ 2.53999582  2.24151944]]


In [5]:
A=np.array([[90,60,90],
            [90,90,30],
            [60,60,60],
             [60,60,90],
            [30,30,30]])

In [6]:
u,s,vt=svd(A.T@A)
print('u: ',u)
print('s: ',s)
print('vt: ', vt)

u:  [[-0.61877743 -0.31692725 -0.71879873]
 [-0.55174883 -0.4759884   0.68484179]
 [-0.55918488  0.820361    0.11966664]]
s:  [62266.64275172  3159.11223306   274.24501522]
vt:  [[-0.61877743 -0.55174883 -0.55918488]
 [-0.31692725 -0.4759884   0.820361  ]
 [-0.71879873  0.68484179  0.11966664]]


In [7]:
np.linalg.eig(A.T@A)

EigResult(eigenvalues=array([62266.64275172,   274.24501522,  3159.11223306]), eigenvectors=array([[-0.61877743, -0.71879873, -0.31692725],
       [-0.55174883,  0.68484179, -0.4759884 ],
       [-0.55918488,  0.11966664,  0.820361  ]]))